apiVersion: ai.sap.com/v1alpha1
kind: WorkflowTemplate
metadata:
  name: expense-audit-job
  annotations:
    scenarios.ai.sap.com/name: "expense-audit"
    scenarios.ai.sap.com/description: "Expense Audit Job - Workflow"
  labels:
    scenarios.ai.sap.com/id: "expense-audit"

spec:
  entrypoint: main

  templates:
  - name: main
    metadata:
      labels:
        ai.sap.com/resourcePlan: starter

    container:
      image: ghcr.io/amyge666/expense-audit-job:main
      command:
        - python
      args:
        - main.py

      env:
      - name: HANA_HOST
        valueFrom:
          secretKeyRef:
            name: hana-credentials
            key: host

      - name: HANA_PORT
        valueFrom:
          secretKeyRef:
            name: hana-credentials
            key: port

      - name: HANA_USER
        valueFrom:
          secretKeyRef:
            name: hana-credentials
            key: user

      - name: HANA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: hana-credentials
            key: password

      - name: HANA_SCHEMA
        value: "EXPENSE_SCHEMA"
